/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package rpc.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RpcFileSplit {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RpcFileSplit\",\"namespace\":\"rpc.service\",\"types\":[{\"type\":\"record\",\"name\":\"FileSplit\",\"namespace\":\"rpc.domain\",\"fields\":[{\"name\":\"path\",\"type\":[\"string\",\"null\"]},{\"name\":\"start\",\"type\":[\"long\",\"null\"]},{\"name\":\"length\",\"type\":[\"long\",\"null\"]}]}],\"messages\":{\"sendFileSplit\":{\"request\":[{\"name\":\"fileSplit\",\"type\":\"rpc.domain.FileSplit\"}],\"response\":\"null\"}}}");
  java.lang.Void sendFileSplit(rpc.domain.FileSplit fileSplit) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends RpcFileSplit {
    public static final org.apache.avro.Protocol PROTOCOL = rpc.service.RpcFileSplit.PROTOCOL;
    void sendFileSplit(rpc.domain.FileSplit fileSplit, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}