/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AddService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AddService\",\"namespace\":\"avro.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"cn.gao\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"gender\",\"type\":[\"string\",\"null\"]},{\"name\":\"age\",\"type\":[\"int\",\"null\"]}]}],\"messages\":{\"add\":{\"request\":[{\"name\":\"x\",\"type\":\"int\"},{\"name\":\"y\",\"type\":\"int\"}],\"response\":\"int\"},\"sendUser\":{\"request\":[{\"name\":\"user\",\"type\":\"cn.gao.User\"}],\"response\":\"null\"}}}");
  /**
   */
  int add(int x, int y) throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.lang.Void sendUser(cn.gao.User user) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AddService {
    public static final org.apache.avro.Protocol PROTOCOL = avro.protocol.AddService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void add(int x, int y, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendUser(cn.gao.User user, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}